import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import RouteCorrecter from "@/components/RouteCorrecter";
import AppSidebar from "@/components/Sidebar";
import QuickOptions from "@/components/QuickOptions";
import ChatLayout from "@/components/Chat/ChatLayout";
import { cn, scrollbarStyle } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning className={cn("w-full h-full")}>
        <body
          suppressHydrationWarning
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full flex`}
        >
          <Providers>
            <RouteCorrecter />
            <div className="relative flex-1 flex">
              <AppSidebar />
              <QuickOptions />

              <main className={cn("flex-1 flex overflow-y-auto", scrollbarStyle)}>
                <div className="flex-1 flex flex-col max-w-3xl mx-auto">
                  <ChatLayout>
                    {children}
                  </ChatLayout>
                </div>
              </main>
            </div>
          </Providers>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
